### ISSUE TITLE
errors when viewing existing storage rack

### ISSUE THREAD

**Issue by khzhu** [senaite/senaite.storage#13]
## Steps to reproduce
1. select any sample storages eg. NYU facility 01
2. select any containers of the selected sample storage eg. fridge 01
3. select any sample container in the select container e.g rack1

## Current behavior
error while rendering plone.contentactions 
## Expected behavior
no errors
## Screenshot (optional)
<img width="1534" alt="Screen Shot 2020-03-02 at 4 14 58 PM" src="https://user-images.githubusercontent.com/17375786/75718603-3ceee280-5ca1-11ea-9cc3-5e3b7ab4dc83.png">

**Comment by khzhu** [comment]
here is what logged on the server.
```
2020-03-02T21:01:28 ERROR plone.app.viewletmanager Error while rendering viewlet-manager=plone.contentviews, viewlet=plone.contentactions
Traceback (most recent call last):
  File "/home/senaite/buildout-cache/eggs/plone.app.viewletmanager-2.0.11-py2.7.egg/plone/app/viewletmanager/manager.py", line 112, in render
    html.append(viewlet.render())
  File "/home/senaite/buildout-cache/eggs/plone.app.layout-2.3.18-py2.7.egg/plone/app/layout/viewlets/common.py", line 50, in render
    return self.index()
  File "/home/senaite/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/senaite/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/senaite/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/senaite/buildout-cache/eggs/five.pt-2.2.4-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/home/senaite/buildout-cache/eggs/z3c.pt-3.2.0-py2.7.egg/z3c/pt/pagetemplate.py", line 173, in render
    return base_renderer(**context)
  File "/home/senaite/buildout-cache/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/zpt/template.py", line 306, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/senaite/buildout-cache/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/template.py", line 187, in render
    self._render(stream, econtext, rcontext)
  File "eb21922ac150b07233e6a6a633bd9a40.py", line 334, in render
  File "/home/senaite/buildout-cache/eggs/z3c.pt-3.2.0-py2.7.egg/z3c/pt/expressions.py", line 73, in render_content_provider
    return cp.render()
  File "/home/senaite/buildout-cache/eggs/plone.app.contentmenu-2.0.12-py2.7.egg/plone/app/contentmenu/view.py", line 20, in render
    return self.index()
  File "/home/senaite/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/senaite/buildout-cache/eggs/Zope2-2.13.28-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/senaite/buildout-cache/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/senaite/buildout-cache/eggs/five.pt-2.2.4-py2.7.egg/five/pt/engine.py", line 98, in __call__
    return self.template.render(**kwargs)
  File "/home/senaite/buildout-cache/eggs/z3c.pt-3.2.0-py2.7.egg/z3c/pt/pagetemplate.py", line 173, in render
    return base_renderer(**context)
  File "/home/senaite/buildout-cache/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/zpt/template.py", line 306, in render
    return super(PageTemplate, self).render(**_kw)
  File "/home/senaite/buildout-cache/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/template.py", line 209, in render
    raise_with_traceback(exc, tb)
  File "/home/senaite/buildout-cache/eggs/Chameleon-3.6.2-py2.7.egg/chameleon/template.py", line 187, in render
    self._render(stream, econtext, rcontext)
  File "e4554722a9d0e66a3f0bcb9c312c1283.py", line 313, in render
  File "/home/senaite/buildout-cache/eggs/five.pt-2.2.4-py2.7.egg/five/pt/expressions.py", line 154, in __call__
    base = self.traverse(base, request, path_items)
  File "/home/senaite/buildout-cache/eggs/five.pt-2.2.4-py2.7.egg/five/pt/expressions.py", line 126, in traverse
    base, name, path_items[i:], request=request
  File "/home/senaite/buildout-cache/eggs/zope.traversing-3.13.2-py2.7.egg/zope/traversing/adapters.py", line 136, in traversePathElement
    return traversable.traverse(nm, further_path)
  File "/home/senaite/buildout-cache/eggs/zope.traversing-3.13.2-py2.7.egg/zope/traversing/adapters.py", line 50, in traverse
    raise LocationError(subject, name)
LocationError: ({'disabled': False, 'id': 'plone-contentmenu-display'}, 'stateTitle')

```

**Comment by ramonski** [comment]
Hi @khzhu,
which versions of `senaite.core` and `senaite.lims` are you using?
This looks to me like you are using partly source distributions that are at the moment heavily under development and code movement.

**Comment by khzhu** [comment]
HI @ramonski , I am using 1.3.2 senaite.core and 1.3.2 senaite.lims.

**Comment by ramonski** [comment]
Should work with new versions
